name = "toby-dev-processor"
main = "src/worker.ts"
compatibility_date = "2024-08-03"
workers_dev = true

[[queues.consumers]]
queue = "toby-dev-queue"
max_batch_size = 1
max_batch_timeout = 1

[[queues.producers]]
queue = "toby-dev-browser-queue"
binding = "TBQ"

[[d1_databases]]
binding = 'DB'
database_name = 'toby_dev_database'
database_id = '<REMOVED>'
