name = "toby-processing"
main = "worker.ts"
compatibility_date = "2023-08-23"

[[queues.consumers]]
queue = "tobyqueue"
max_batch_size = 1
max_batch_timeout = 1

[[d1_databases]]
binding = 'DB'
database_name = 'mtg_discord_tourney_bot'
database_id = '<REMOVED>'
